#!/bin/sh
#
# Building vmensa
#

# Do the build.
cabal build "vmensa"

# Install manpage
sudo cp ./man/vmensa.1 /usr/local/share/man/man1
if type mandb > /dev/null 2>&1; then
  sudo mandb
fi

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T $(cabal exec -- which "vmensa" 2> /dev/null) "$1"
