#!/bin/sh
#
# Building vmensa
#

# Do the build.
stack build "vmensa"

# Install manpage
sudo cp ./man/vmensa.1 /usr/local/share/man/man1
if type mandb > /dev/null 2>&1; then
  sudo mandb
fi

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T $(stack exec -- which "vmensa") "$1"
