name:                vmensa
version:             0.1.0
homepage:            https://gitlab.com/slotThe/vmensa
synopsis:            Query the Stundentenwerk API from inside your terminal!
license:             GPL-3
author:              Tony Zorman
maintainer:          tonyzorman@mailbox.org

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -O2

default-extensions:
  - ImportQualifiedPost
  - OverloadedStrings
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - InstanceSigs
  - TypeApplications
  - ScopedTypeVariables
  - BangPatterns
  - NamedFieldPuns
  - DuplicateRecordFields
  - BlockArguments
  - LambdaCase
  - StrictData

library:
  source-dirs: lib

dependencies:
  - name: base
    mixin: hiding (Prelude)
  - base-prelude
  - containers
  - aeson
  - async
  - http-client
  - http-client-tls
  - text
  - time                 >= 1.9
  - optparse-applicative
  - optparse-applicative-util
  - attoparsec

executables:
  vmensa:
    source-dirs: app
    main: Main.hs
    dependencies: vmensa
    ghc-options:
      -threaded
      -with-rtsopts=-N
