name:                vmensa
version:             0.1.0
synopsis:            Query the Stundentenwerk API from inside your terminal!
license:             GPL-3
author:              Tony Zorman
maintainer:          tonyzorman@mailbox.org

default-extensions:
  - OverloadedStrings
  - TypeApplications
  - NamedFieldPuns
  - DeriveAnyClass
  - DeriveGeneric
  - InstanceSigs
  - LambdaCase
  - BangPatterns
  - DuplicateRecordFields
  - BlockArguments
  - ScopedTypeVariables

ghc-options:
  -O2
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints

dependencies:
  - base-noprelude
  - base-prelude
  - aeson
  - async
  - http-conduit
  - text
  - time                  >= 1.9
  - optparse-applicative
  - attoparsec

executables:
  vmensa:
    source-dirs: src
    main: Main.hs
    ghc-options:
     -threaded
     -with-rtsopts=-N
