name:                vmensa
version:             0.1.0
homepage:            https://gitlab.com/tozor/vmensa
synopsis:            Query the Stundentenwerk API from inside your terminal!
license:             GPL-3
author:              Tony Zorman
maintainer:          tonyzorman@mailbox.org

default-extensions:
  - OverloadedStrings
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - InstanceSigs
  - TypeApplications
  - ScopedTypeVariables
  - BangPatterns
  - NamedFieldPuns
  - DuplicateRecordFields
  - BlockArguments
  - LambdaCase
  - StrictData

ghc-options:
  -O2
  -funbox-strict-fields
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints

library:
  source-dirs: lib

dependencies:
  - name: base
    mixin: hiding (Prelude)
  - base-prelude
  - containers
  - aeson
  - async
  - http-conduit
  - text
  - time                 >= 1.9
  - optparse-applicative
  - optparse-applicative-util
  - attoparsec

executables:
  vmensa:
    source-dirs: app
    main: Main.hs
    dependencies: vmensa
    ghc-options:
      -threaded
      -with-rtsopts=-N
