name:                vmensa
version:             0.3.0
homepage:            https://gitlab.com/slotThe/vmensa
synopsis:            Query the Stundentenwerk API from inside your terminal!
license:             GPL-3
author:              Tony Zorman
maintainer:          tonyzorman@mailbox.org

extra-doc-files: man/*.1

ghc-options:
  -Weverything
  -Wno-implicit-prelude
  -Wno-missing-import-lists
  -Wno-unused-packages
  -Wno-missing-safe-haskell-mode
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -Wno-name-shadowing
  -Wno-missing-role-annotations
  -Wno-x-partial
  -O2

default-extensions:
  - NoImplicitPrelude
  - ImportQualifiedPost
  - OverloadedStrings
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - InstanceSigs
  - TypeApplications
  - ScopedTypeVariables
  - BangPatterns
  - NamedFieldPuns
  - DuplicateRecordFields
  - BlockArguments
  - LambdaCase
  - StrictData
  - StandaloneKindSignatures
  - ViewPatterns
  - DataKinds
  - GADTs
  - KindSignatures
  - FlexibleInstances
  - RecordWildCards

library:
  source-dirs: lib

dependencies:
  - base
  - base-prelude
  - containers
  - aeson
  - async
  - http-client
  - http-client-tls
  - text
  - time                 >= 1.9
  - optparse-applicative
  - optparse-applicative-cmdline-util
  - attoparsec
  - cmdline-util
  - html-parse
  - html-parse-util
  - bytestring
  - scalpel
  - tagsoup

executables:
  vmensa:
    source-dirs: app
    main: Main.hs
    dependencies: vmensa
    ghc-options:
      -threaded
      -with-rtsopts=-N
    #   -static
    # cc-options: -static
    # ld-options: -static -pthread
