resolver: lts-21.9

packages:
- .

extra-deps:
  - git: https://gitlab.com/slotThe/optparse-applicative-util
    commit: 9b3125b6f54618f7e6e0f4303a0e4173261283f7
  - git: https://gitlab.com/slotThe/cmdline-util
    commit: 1e75b67c8948e252ef3758c69efbf6a7ffa4c44d
