resolver: lts-20.0

packages:
- .

extra-deps:
  - git: https://gitlab.com/slotThe/optparse-applicative-util
    commit: 23230d069881412a727d5d7d2c7cb19dad14312d
  - git: https://gitlab.com/slotThe/cmdline-util
    commit: 1e75b67c8948e252ef3758c69efbf6a7ffa4c44d
